### ISSUE TITLE
Support for Swift4?

### ISSUE THREAD

**Issue by kpavankotesh** [Sali0m/JVMaskView#1]
Is it possible to upgrade his pod to Swift 4? Thanks

**Comment by Sali0m** [comment]
Sure, I'll try to do it on my lunch time today, I'll keep you posted :)

**Comment by Sali0m** [comment]
It should be fine with the 1.0.1 version now, can you test it and tell me if anything is missing? (not used to update cocoapods)

**Comment by kpavankotesh** [comment]
@Sali0m We just checked the update and it works. Thanks for the quick response.
